# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a90434b6bd4ea938fb4e0e9a445cc8734a44c5478f82ebd6023da6c231f4fdc79c6e63f38623b6840bb24028227836670d58195fae0e31baedb09c53b1a74651

test:
  secret_key_base: 39fa319ad557d3320b64046d4388b25942af10043ac947b1e423618d8dd663011d7a1a50ef39d735641711c604b87e820fe21b35124e3b7be3ed97904de61d7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
